### ISSUE TITLE
Save  / load / new project

### ISSUE THREAD

**Issue by GuillaumeLazar** [neuronalmotion/blueprint#86]

**Comment by GuillaumeLazar** [comment]
@synapticvoid : I think we should work together on this one the 9th october. What do you think about it?

**Comment by synapticvoid** [comment]
I was avoing this issue precisely for that reason, so yeah!

**Comment by synapticvoid** [comment]
http://programmers.stackexchange.com/questions/294286/c-serialization-design-review

I like the solution proposed by Amon. I didn't want that our Model classes know about the serialization format (XML/JSON or anything else), but it's also true that **they** know how to serialize/deserialize themselves.

This solution seems elegant to me because it offers:
- An intermediate `SerializationInfo` which is agnostic of the serialization format
- No need to expose `Shape` internals for a third-party Manager which would grow into a monster anyway
- No need to declare a specific serializer for each `Shape`, by doing this we enforce a a friend class, which defeats the whole purpose of decoupling `Shape` from its serialization format.

Thinking about it, in Android, exactly the same strategy is used for IPC using `Parcelable` interface. The objet knows how to export/load itself, it just does not need to know what will be the final format.

**Comment by GuillaumeLazar** [comment]
I like the idea even if I don't understand yet how to do it completely :smile: 
I never implemented this kind of generic serialization design, let's do it!

**Comment by synapticvoid** [comment]
Possible ideas for the internals of `SerializationInfo` :
- `QMap<QString, QVariant>`, using the qvariant enables us to put any primitive type without aving to reimplement anything
- Register our Shape classes to Qt Meta system as `QVariant` compatible : http://www.bogotobogo.com/Qt/Qt5_QVariant_meta_object_system_MetaType.php

**Comment by GuillaumeLazar** [comment]
Ok so good news: we can saved a project from UI :smile: 
Now the bas news, I have some troubles with reloading it... :cry: 

I had UI "Save/Load" and connected to Xml/parcel stuff but we have to fix some things:
- Link with `ShapeModel`
- Link with `QGraphicsScene`

A good way to start could be to avoid manipulating the model/scene our self as it's done by the `MainWindow` for the default project. 

An idea could be to load a previously saved project call "default.bpt" (yeah I chose *.bpt do you like it?) and automatically load it on application startup. It will force us to embedded all Model/Scene stuff into into dedicated functions.

Please, see commit 64967e8. You should be able to save a project (_huhu) but crash on load it (_doh).

@synapticvoid What do you thing about that?

**Comment by synapticvoid** [comment]
- Ok for the .bpt extension
- You're right, this code has to be removed from `MainWindow`.

For the test, the ideal would be to complete our tests with this projet, this way we can keep track of what we are testing. If needed, you can instanciate a `MainWindow` in our tests and generates UI events.

For the code, as we discussed, we have to handle the model index generation _and_ the single point of interaction the the blueprint tree. Your WIP shows the right direction, we just have to be able to disable the `ShapeModel`notification system when we are deserizating in `Shape::fromParcel`.
